# Generated by Django 3.2.3 on 2021-06-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('youtube_code', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(verbose_name='date created')),
                ('slug', models.SlugField(blank=True, default='', max_length=100)),
                ('show', models.BooleanField(default=True, null=True)),
                ('categories', models.ManyToManyField(blank=True, to='audiobooks.Category')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
