# Generated by Django 3.2.3 on 2021-06-17 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('categories', models.ManyToManyField(blank=True, to='audiobooks.Category')),
            ],
            options={
                'verbose_name_plural': 'series',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('youtube_code', models.CharField(max_length=20)),
                ('slug', models.SlugField(blank=True, default='', max_length=100)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audiobooks.series')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
